export default {"ja":
	{"showPalette": "パレットを表示",
         "showClipboard": "クリップボードを表示",		 
         "showEllipses": "リストの追加ボタンを表示",		 
         "showDescription": "詳細な説明を表示",
         "enableL18N": "日本語で表示",	 
	 "if.condition": "条件" ,
	 "if.true-case": "条件が真の時" ,
	 "if.false-case": "条件が偽の時",
 	 "let.substitute": "変数の名前と代入される値",
 	 "lambda.args": "入力を表す変数の一覧",
	 "lambda.body": "関数の内容",
	 "description.let": "スコープ変数を定義",
	 "description.if": "条件分岐",
	 "description.annotate": "コードに説明を付ける",
	 "description.lambda": "無名関数を定義して返す",
	 "description.begin": "順番に実行する",
	 "description.quote": "シンボル/リストの定数",
	 "description.quasiquote": "リストのテンプレート",
	 "description.unquote": "テンプレートに代入",
	 "description.define": "変数を定義",
	 "description.list": "リストを作成する",
	 "description.+": "足し算の和を計算",
	 "description.-": "差を計算",
	 "description.*": "積を計算",
	 "description./": "商を計算",
	 "description.%": "割り算の余りを計算",
	 "tooltip.let": "このブロックの中でのみ使える変数を定義します。",
	 "tooltip.if": "条件を評価して#t (真/成り立っている) のとき、１つめの式を評価し返します。それ以外の時、2つめの式を評価し返します。",
	 "tooltip.annotate": "何を計算するコードなのか、説明をつけます。",
	 "tooltip.lambda": "無名関数を定義して返す",
	 "tooltip.begin": "順番に実行し、最後の値を返します。",
	 "tooltip.quote": "シンボルやリストを入力されたとおりに返します。",
	 "tooltip.quasiquote": "リストを作成します",
	 "tooltip.unquote": "テンプレートの中身を計算した値で埋めます。",
	 "tooltip.define": "変数を定義",
	 "tooltip.+": "全ての値を合計した結果を返します。",
	 "tooltip.-": "1つめの値から、2つ目以降の値をすべて引いた値を返します。",
	 "tooltip.*": "全ての値を掛け算した結果を返します。",
	 "tooltip./": "1つめの値から、2つ目以降の値をすべて割った値を返します。",
	 "tooltip.%": "1つめの値を２つ目の値で割り、整数の商とあまりを求め、あまりを返します。",
	},
 "en":
	{"showPalette": "Show Palette",
         "showClipboard": "Show Clipboard",		 
         "showEllipses": "Show Addition Button",		 
         "showDescription": "Show Detailed Help",		 
         "enableL18N": "日本語で表示",		 
	}
}
